---
sidebar: sidebar 
permalink: ontap-security-hardening/autonomous-ransomware-protection.html 
keywords: tr-4569, ontap hardening guide, security, ARP, fpolicy, UBA, ransomware, machine learning, volume workloads, entropy 
summary: Die integrierte Machine-Learning-Funktion von ONTAP erkennt Ransomware anhand von Volume-Workloads und Entropie. 
---
= Autonomer Ransomware-Schutz von ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Als Ergänzung zur Analyse des Benutzerverhaltens für die Sicherheit von Storage-Workloads analysiert der autonome Ransomware-Schutz von ONTAP Volume-Workloads und Entropie, um Ransomware zu erkennen. Er erstellt einen Snapshot und benachrichtigt den Administrator, wenn der Verdacht eines Angriffs besteht.

Zusätzlich zur Ransomware-Erkennung und -Prävention durch externe FPolicy-Benutzerverhaltensanalysen (UBA) mit NetApp Data Infrastructure Insights Storage Workload Security und dem NetApp FPolicy-Partner-Ökosystem führt ONTAP 9.10.1 einen autonomen Ransomware-Schutz ein.  Der autonome Ransomware-Schutz von ONTAP nutzt eine integrierte On-Box-Funktion für maschinelles Lernen (ML), die die Workload-Aktivität des Volumens sowie die Datenentropie berücksichtigt, um Ransomware automatisch zu erkennen.  Es überwacht Aktivitäten, die sich von UBA unterscheiden, sodass es Angriffe erkennen kann, die UBA nicht erkennt.

Weitere Informationen zu dieser Funktion finden Sie unter link:../ransomware-solutions/ransomware-overview.html["NetApp Lösungen für Ransomware"] oder link:https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html["Dokumentation zum autonomen Ransomware-Schutz von ONTAP"^].
