---
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices 
permalink: nas-containers.html 
summary: Diese technischen Berichte geben einen Überblick über die FlexCache und FlexGroup Volumes in NetApp ONTAP sowie Empfehlungen zu Best Practices 
---
= Technische Berichte zu Volumes von FlexCache und FlexGroup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp NAS-Lösungen vereinfachen das Datenmanagement, halten mit dem Datenwachstum Schritt und optimieren gleichzeitig die Kosten. Mit NAS-Lösungen von ONTAP erreichen Sie unterbrechungsfreien Betrieb, bewährte Effizienz und nahtlose Skalierbarkeit in einer Unified Architecture. Scale-out-NAS mit ONTAP Technologie nutzt das enorme ONTAP Ecosystem, in dem wir einen bedeutenden Innovationsvorsprung und auch eine Vision für aggressive zukünftige Innovationen haben.

[NOTE]
====
Diese technischen Berichte werden im erweitert link:https://docs.netapp.com/us-en/ontap/task_nas_flexcache.html["ONTAP FlexCache Volume"] Und link:https://docs.netapp.com/us-en/ontap/task_nas_provision_flexgroup.html["ONTAP FlexGroup Volume"] Produktdokumentation:

====


== FlexCache

link:https://www.netapp.com/pdf.html?item=/media/7336-tr4743.pdf["TR-4743: FlexCache im ONTAP"^]
Bei FlexCache handelt es sich um eine Caching-Technologie, die spärliche, beschreibbare Replikate von Volumes auf demselben oder verschiedenen ONTAP Clustern erstellt. Die Software kann den Benutzer näher bringen, um einen schnelleren Durchsatz bei geringerem Platzbedarf zu erzielen. Erfahren Sie, wie FlexCache eingesetzt werden kann sowie über empfohlene Practices, Grenzen und Überlegungen für Design und Implementierung.



== FlexGroup Volumes

link:https://www.netapp.com/pdf.html?item=/media/17251-tr4571a.pdf["TR-4571a: Die zehn wichtigsten Best Practices von FlexGroup"^]
Dieser technische Bericht ist eine komprimierte Version des TR-4571: NetApp ONTAP FlexGroup Volumes Best Practices and Implementation Guide für den schnellen Verbrauch.

link:https://www.netapp.com/pdf.html?item=/media/7337-tr4557.pdf["TR-4557: NetApp ONTAP FlexGroup Volumes – technischer Überblick"^]
Erfahren Sie mehr über FlexGroup Volumes, einen ONTAP Scale-out-NAS-Container, der nahezu unbegrenzte Kapazität mit einer vorhersehbaren Performance mit niedriger Latenz bei Workloads mit Metadaten kombiniert.

link:https://www.netapp.com/pdf.html?item=/media/12385-tr4571.pdf["TR-4571: NetApp ONTAP FlexGroup Volumes Best Practices und Implementierungsleitfaden"^]
Erfahren Sie mehr über FlexGroup Volumes sowie empfohlene Practices und Implementierungstipps. FlexGroup Volumes sind eine Weiterentwicklung von ONTAP-Scale-out-NAS-Containern, die nahezu unbegrenzte Kapazität mit einer planbaren Performance mit niedriger Latenz für Workloads mit vielen Metadaten verbinden.

link:https://www.netapp.com/pdf.html?item=/media/17064-tr4678.pdf["TR-4678: Datensicherheit und Backup von FlexGroup Volumen"^]
Informieren Sie sich über Datensicherung und Backup für FlexGroup Volumes, einschließlich Snapshot Kopien, SnapMirror und anderen Datensicherungs- und Backup-Lösungen.
