---
permalink: networking.html 
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices 
summary: Diese technischen Berichte bieten einen Überblick über das Networking in NetApp ONTAP sowie empfohlene Vorgehensweisen. 
---
= Technische Berichte zum ONTAP Networking
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP bietet eine Vielzahl verschiedener Netzwerkfunktionen und Konfigurationen für anspruchsvollste Scale-out-Applikationen. Mithilfe der Netzwerkfunktionen und -Funktionen können Unternehmen einen zuverlässigen und sicheren Zugriff auf ihre Daten schaffen.

[NOTE]
====
Diese technischen Berichte erweitern die link:https://docs.netapp.com/us-en/ontap/network-management/index.html["ONTAP-Netzwerkmanagement"^]Produktdokumentation.

====


[[routing]]
== Routing

link:https://www.netapp.com/pdf.html?item=/media/79703-TR-4949.pdf["TR-4949: BGP/VIP mit ONTAP im Rechenzentrum"^]
Erfahren Sie, wie Sie eine grundlegende BGP-Konfiguration in ONTAP schnell implementieren.



[[name-services]]
== Name Services

link:https://www.netapp.com/pdf.html?item=/media/19370-tr-4523.pdf["TR-4523: DNS-Lastverteilung in ONTAP"^]
Erfahren Sie, wie Sie ONTAP für die Verwendung mit DNS-Lastausgleichsmethoden konfigurieren, einschließlich DNS in ONTAP, verschiedene Konfigurationsmethoden und empfohlene Vorgehensweisen.

link:https://www.netapp.com/pdf.html?item=/media/16328-tr-4668.pdf["TR-4668: Name Services Best Practices Guide"^]
Erfahren Sie mehr über empfohlene Vorgehensweisen, Einschränkungen und Überlegungen bei der Implementierung von NAS-Lösungen (Network-Attached Storage) wie CIFS/SMB und NFS in ONTAP.

link:https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf["TR-4835: Konfiguration von LDAP in ONTAP-Multiprotokoll-NAS-Identitätsmanagement"^]
Erfahren Sie, wie Sie das Lightweight Directory Access Protocol (LDAP)-Identitätsmanagement in ONTAP für Multiprotokoll-NAS konfigurieren.
