---
settings:
  name: ONTAP technical reports
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Technische Berichte von ONTAP
    url: "/index.html"
  - title: Technische Berichte zu Applikationen und Datenbanken
    url: "/apps-dbs.html"
  - title: Technische Berichte zur Business Continuity
    url: "/business-continuity.html"
  - title: Technische Berichte zur Datensicherung und Disaster Recovery
    url: "/data-protection-disaster-recovery.html"
  - title: Technische Berichte zu FlexCache und FlexGroup Volumes
    url: "/nas-containers.html"
  - title: Technische Berichte von NAS
    url: "/nas.html"
  - title: Technische Netzwerkberichte
    url: "/networking.html"
  - title: TECHNISCHE BERICHTE ZU SAN
    url: "/san.html"
  - title: Technische Sicherheitsberichte
    url: "/security.html"
  - title: Leitfäden zur Erhöhung der Sicherheit
    url: "/security-hardening-guides.html"
  - title: Technische Berichte von SnapCenter
    url: "/snapcenter.html"
  - title: Tiering von technischen Berichten
    url: "/tiering.html"
  - title: Technische Berichte zur Virtualisierung
    url: "/virtualization.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
