---
settings:
  name: ONTAP Technical Reports
  search: ontap-technical-reports, ontap-apps-dbs, netapp-solutions-sap
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Technische Berichte zu ONTAP
    url: "/index.html"
  - title: Applikationen und Datenbanken
    url: "/apps-dbs.html"
  - title: Business Continuity Remote replizieren
    url: "/business-continuity.html"
  - title: Datensicherung und Disaster Recovery
    url: "/data-protection-disaster-recovery.html"
  - title: FlexCache und FlexGroup Volumes
    url: "/nas-containers.html"
  - title: NAS
    url: "/nas.html"
  - title: Netzwerkbetrieb
    url: "/networking.html"
  - title: San
    url: "/san.html"
  - title: Sicherheit
    entries:
    - title: Überblick
      url: "/security.html"
    - section: ransomware-solutions
    - section: zero-trust
    - section: abac
  - title: Verstärkte Sicherheit
    entries:
    - title: Überblick
      url: "/security-hardening-guides.html"
    - section: ontap-security-hardening
  - title: SnapCenter
    url: "/snapcenter.html"
  - title: Tiering
    url: "/tiering.html"
  - title: Einheitliche
    url: "/virtualization.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
