---
settings:
  name: ONTAP technical reports
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Technische Berichte von ONTAP
    url: "/index.html"
  - title: Applikationen und Datenbanken
    url: "/apps-dbs.html"
  - title: Business Continuity Remote replizieren
    url: "/business-continuity.html"
  - title: Datensicherung und Disaster Recovery
    url: "/data-protection-disaster-recovery.html"
  - title: FlexCache und FlexGroup Volumes
    url: "/nas-containers.html"
  - title: NAS
    url: "/nas.html"
  - title: Netzwerkbetrieb
    url: "/networking.html"
  - title: San
    url: "/san.html"
  - title: Sicherheit
    url: "/security.html"
  - title: Leitfäden zur Erhöhung der Sicherheit
    url: "/security-hardening-guides.html"
  - title: SnapCenter
    url: "/snapcenter.html"
  - title: Tiering
    url: "/tiering.html"
  - title: Einheitliche
    url: "/virtualization.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
