---
permalink: storage-efficiency.html 
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices 
summary: Diese technischen Berichte bieten einen Überblick über die Storage-Effizienz in NetApp ONTAP sowie empfohlene Vorgehensweisen. 
---
= Technische Berichte zur ONTAP Storage-Effizienz
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP bietet ein umfassendes Portfolio an Funktionen für effizienteren Storage. Inline-Datenkomprimierung, -Deduplizierung und -Data-Compaction sorgen zusammen für niedrigere Storage-Kosten und eine maximale effektive Datenkapazität. Außerdem können Sie Ihre Einsparungen mit platzsparenden NetApp Snapshot Kopien, Thin Provisioning, Replizierung und Klontechnologien vervielfachen.

[NOTE]
====
Die Verfahrensdokumentation für die Deduplizierung finden Sie in der link:https://docs.netapp.com/us-en/ontap/volumes/enable-deduplication-volume-task.html["Dokumentation der Deduplizierung"^] Verfahrensdokumentation für die Komprimierung link:https://docs.netapp.com/us-en/ontap/volumes/enable-data-compression-volume-task.html["Dokumentation der Komprimierung"^]unter Verfahrensdokumentation für die temperaturempfindliche Speichereffizienz finden Sie link:https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html["Dokumentation zur temperaturempfindlichen Storage-Effizienz"^]unter Verfahrensdokumentation für die Data-Compaction link:https://docs.netapp.com/us-en/ontap/volumes/enable-inline-data-compaction-fas-systems-task.html["Data-Compaction-Dokumentation"^]

====