---
layout: landing-page 
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, VMware, vVols, SRM, SRA, Site Recovery Manager, OTV, ONTAP Tools for VMware, SnapCenter for VMware, SnapCenter, RCU, VSC, Virtual Storage Console, best practices, best-practices 
permalink: virtualization.html 
summary: Diese technischen Berichte bieten einen Überblick über die VMware Virtualisierungslösungen mithilfe von NetApp ONTAP sowie empfohlene Vorgehensweisen. 
---
= Technische Berichte zur Virtualisierung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Virtualisierungslösungen helfen Ihnen, den maximalen Nutzen aus Ihren Servern zu ziehen. Mit einer reaktionsschnellen virtuellen Serverinfrastruktur, die auf zukunftsweisenden, hochleistungsfähigen ONTAP Flash-Systemen basiert, können Sie schneller auf Ihre Daten zugreifen. Eine granulare virtuelle Infrastruktur lässt sich unterbrechungsfrei auf Datenmengen im Petabyte-Bereich skalieren und bietet die Performance, die für den gemeinsamen Zugriff auf mehrere Workloads erforderlich ist. ONTAP trägt durch wichtige Partnerschaften, Implementierungsanleitungen, Applikationsintegration und ein ausgereiftes Design dazu bei, den Einsatz von virtuellen Serverinfrastrukturen einfacher zu machen. ONTAP bietet viele empfohlene Praktiken und Lösungen für eine robuste Virtualisierungsumgebung sowohl vor Ort als auch in der Cloud.

Diese technischen Berichte werden im erweitert link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["ONTAP Tools für VMware vSphere"] Produktdokumentation:

link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597: VMware vSphere für ONTAP"]
 ONTAP ist seit fast zwei Jahrzehnten eine der führenden Storage-Lösungen für VMware vSphere Umgebungen und wird kontinuierlich mit innovativen Funktionen erweitert, die nicht nur zur Vereinfachung des Managements, sondern auch zu Kostensenkungen beitragen. Dieses Dokument bietet eine Einführung in die ONTAP Lösung für vSphere sowie in die neuesten Produktinformationen und empfohlenen Vorgehensweisen zur Optimierung der Implementierung, Risikominderung und Vereinfachung des Managements.

link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vvols-overview.html["TR-4400: VMware vSphere Virtual Volumes (VVols) mit NetApp ONTAP"]
ONTAP ist seit über zwei Jahrzehnten eine der führenden Storage-Lösungen für VMware vSphere Umgebungen und wird kontinuierlich mit innovativen Funktionen erweitert, die nicht nur zur Vereinfachung des Managements, sondern auch zu Kostensenkungen beitragen. Dieses Dokument behandelt die ONTAP Funktionen für VMware vSphere Virtual Volumes (VVols), einschließlich der neuesten Produktinformationen und Anwendungsfälle sowie empfohlene Vorgehensweisen und andere Informationen zur Optimierung der Implementierung und Reduzierung von Fehlern.

link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsrm-ontap9_1._introduction_to_srm_with_ontap.html["TR-4900: VMware Site Recovery Manager mit NetApp ONTAP"]
ONTAP ist seit seiner Einführung in das moderne Datacenter im Jahr 2002 eine der führenden Storage-Lösungen für VMware vSphere Umgebungen und wird kontinuierlich um innovative Funktionen erweitert, die nicht nur zur Vereinfachung des Managements, sondern auch zu Kostensenkungen beitragen. Dieses Dokument bietet eine Einführung in die ONTAP Lösung für VMware Site Recovery Manager (SRM), die branchenführende Disaster Recovery (DR)-Software von VMware. Sie enthält die neuesten Produktinformationen und empfohlene Verfahren, um die Implementierung zu optimieren, Risiken zu reduzieren und das fortlaufende Management zu vereinfachen.

link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_auto_introduction.html["Einführung in die Automatisierung für ONTAP und vSphere"]
Seit den ersten Tagen von VMware ESX ist die Automatisierung ein integraler Bestandteil des Managements von VMware Umgebungen. Die Möglichkeit, Infrastruktur als Code zu implementieren und Verfahren auf private Cloud-Vorgänge auszuweiten, um Bedenken hinsichtlich Skalierbarkeit, Flexibilität, Self-Provisioning und Effizienz zu zerstreuen. In diesem Dokument wird die ONTAP Lösung zur Automatisierung der ONTAP- und VMware vSphere-Umgebung vorgestellt.

link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/tools-vmware-secure-development-activities.html["WP-7353: ONTAP Tools for VMware vSphere – Product Security"]
In diesem Dokument werden die Techniken und Technologien beschrieben, mit denen ONTAP-Tools für VMware vSphere 9.X sowohl vor vorhandenen als auch vor neuen Bedrohungen in Produktumgebungen gesichert werden.

link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/tools-vmware-secure-development-activities.html["WP-7355: SnapCenter Plug-in VMware vSphere – Produktsicherheit"]
In diesem Dokument werden die Techniken und Technologien beschrieben, mit denen das NetApp SnapCenter Plug-in für VMware vSphere 4.X sowohl vor vorhandenen als auch vor neuen Bedrohungen in Produktumgebungen gesichert wird.
