---
permalink: zero-trust/zero-trust-automation-orchestration.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, ontap, netapp, security, automation, orchestration, control, ansible 
summary: Durch Automatisierung sind Unternehmen in der Lage, Zero-Trust-Implementierungen über manuelle Verfahren hinaus zu skalieren und so gegen missbräuchliche Aktivitäten zu schützen, die ebenfalls automatisiert werden 
---
= Kontrollmechanismen für die Sicherheitsautomatisierung und Orchestrierung von NetApp außerhalb von ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch Automatisierung können Sie Prozesse oder Verfahren mit minimaler menschlicher Unterstützung durchführen. Durch Automatisierung sind Unternehmen in der Lage, Zero-Trust-Implementierungen weit über manuelle Verfahren hinaus zu skalieren und sich so gegen ebenfalls automatisierte Aktivitäten zu wehren, bei denen Fehlkreationen entstehen.

Ansible ist ein Open-Source-Tool für Softwarebereitstellung, Konfigurationsmanagement und Anwendungsdeployment. Es läuft auf vielen Unix-ähnlichen Systemen und kann sowohl diese als auch Microsoft Windows konfigurieren. Es enthält eine eigene deklarative Sprache zur Beschreibung der Systemkonfiguration. Ansible wurde von Michael DeHaan entwickelt und 2015 von Red Hat übernommen. Ansible arbeitet agentenlos, stellt temporär eine Remote-Verbindung über SSH oder Windows Remote Management her (was die Remote PowerShell-Ausführung ermöglicht), um Aufgaben auszuführen. NetApp hat mehr als  https://www.netapp.com/devops/ansible/["150 Ansible-Module für ONTAP-Software"^] entwickelt, was eine weitere Integration mit dem Ansible Automation Framework ermöglicht. Ansible-Module für NetApp liefern Anweisungen, wie der gewünschte Zustand definiert und an die Zielumgebung von NetApp übermittelt wird. Module unterstützen Aufgaben wie das Einrichten von Lizenzen, das Erstellen von Aggregaten und Storage Virtual Machines, das Erstellen von Volumes und das Wiederherstellen von Snapshots, um nur einige zu nennen. Eine Ansible-Rolle wurde  https://github.com/NetApp/ansible/tree/master/nar_ontap_security_ucd_guide["Veröffentlicht auf GitHub"^] spezifisch für den NetApp DoD Unified Capabilities (UC) Deployment Guide entwickelt.

Mit der Bibliothek verfügbarer Module können Benutzer auf einfache Weise Ansible-Playbooks entwickeln und für die eigenen Applikationen und geschäftlichen Anforderungen anpassen, um Routineaufgaben zu automatisieren. Nachdem ein Playbook verfasst ist, können Sie es ausführen, um die angegebene Aufgabe auszuführen. Dies spart Zeit und erhöht die Produktivität. NetApp hat Beispiel-Playbooks erstellt und geteilt, die direkt verwendet oder an die eigenen Anforderungen angepasst werden können.

Data Infrastructure Insights ist ein Tool zur Infrastrukturüberwachung, das Ihnen Einblick in Ihre gesamte Infrastruktur gibt.  Mit Data Infrastructure Insights können Sie alle Ihre Ressourcen überwachen, Fehler beheben und optimieren, einschließlich Ihrer öffentlichen Cloud-Instanzen und Ihrer privaten Rechenzentren.  Data Infrastructure Insights kann die durchschnittliche Zeit bis zur Lösung um 90 % verkürzen und verhindern, dass 80 % der Cloud-Probleme Endbenutzer betreffen.  Darüber hinaus können Sie die Kosten für die Cloud-Infrastruktur um durchschnittlich 33 % senken und Ihre Anfälligkeit gegenüber Insider-Bedrohungen verringern, indem Sie Ihre Daten mit verwertbaren Informationen schützen.  Die Storage Workload Security-Funktion von Data Infrastructure Insights ermöglicht die Analyse des Benutzerverhaltens mit KI und ML, um zu warnen, wenn aufgrund einer Insider-Bedrohung abweichendes Benutzerverhalten auftritt.  Für ONTAP nutzt Storage Workload Security die Zero Trust FPolicy-Engine.
