---
permalink: zero-trust/zero-trust-cloud-deployments.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, netapp, cloud, deployments, hybrid, amazon web services, aws, microsoft azure, google cloud platform, gcp, GCNV, Google Cloud, Google Cloud NetApp Volumes 
summary: NetApp Optionen erweitern lokale Datenmanagementsysteme auf die Hybrid Cloud mit führenden Cloud-Providern und unterstützen Zero-Trust-Sicherheitskontrollen 
---
= Zero-Trust- und Hybrid-Cloud-Implementierungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp ist die Datenautorität für die Hybrid Cloud. NetApp bietet eine Vielzahl von Optionen zur Erweiterung lokaler Datenmanagementsysteme auf die Hybrid Cloud mit Amazon Web Services (AWS), Microsoft Azure, Google Cloud und anderen führenden Cloud-Anbietern. NetApp Hybrid-Cloud-Lösungen unterstützen dieselben Zero Trust-Sicherheitskontrollen, die auch für lokale ONTAP -Systeme und softwaredefinierten ONTAP Select Speicher verfügbar sind.

Sie können die Kapazität in öffentlichen Clouds ohne die typischen CAPEX-Einschränkungen problemlos erweitern, indem Sie Cloud-native Dateidienste der Enterprise-Klasse für AWS (FSxN), Google Cloud (GCNV) und Azure NetApp Files für Microsoft Azure verwenden. Diese Cloud-Datendienste eignen sich ideal für datenintensive Workloads wie Analysen und DevOps und kombinieren elastischen On-Demand-Speicher als Service von NetApp mit ONTAP Datenmanagement in einem vollständig verwalteten Angebot.

ONTAP ermöglicht die Datenübertragung zwischen Ihren lokalen ONTAP -Systemen und der AWS-, Google Cloud- oder Azure-Speicherumgebung mit der Datenreplikationssoftware NetApp SnapMirror .
