---
permalink: zero-trust/zero-trust-automation-orchestration.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, ontap, netapp, security, automation, orchestration, control, ansible 
summary: Durch Automatisierung sind Unternehmen in der Lage, Zero-Trust-Implementierungen über manuelle Verfahren hinaus zu skalieren und so gegen missbräuchliche Aktivitäten zu schützen, die ebenfalls automatisiert werden 
---
= Kontrollmechanismen für die Sicherheitsautomatisierung und Orchestrierung von NetApp außerhalb von ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch Automatisierung können Sie Prozesse oder Verfahren mit minimaler menschlicher Unterstützung durchführen. Durch Automatisierung sind Unternehmen in der Lage, Zero-Trust-Implementierungen weit über manuelle Verfahren hinaus zu skalieren und sich so gegen ebenfalls automatisierte Aktivitäten zu wehren, bei denen Fehlkreationen entstehen.

Ansible ist ein Open-Source-Tool zur Softwarebereitstellung, zum Konfigurationsmanagement und zur Applikationsbereitstellung. Es läuft auf vielen Unix-ähnlichen Systemen und kann sowohl Unix-ähnliche Systeme als auch Microsoft Windows konfigurieren. Es enthält seine eigene deklarative Sprache, um die Systemkonfiguration zu beschreiben. Ansible wurde von Michael DeHaan geschrieben und 2015 von Red hat übernommen. Ansible funktioniert ohne Agenten und stellt zur Durchführung von Aufgaben vorübergehend eine Remote-Verbindung über SSH oder Windows Remote Management her (sodass PowerShell Remote ausgeführt werden kann). NetApp hat mehr als entwickelt https://www.netapp.com/us/getting-started-with-netapp-approved-ansible-modules/index.aspx["150 Ansible-Module für ONTAP-Software"^]und ermöglicht eine weitere Integration in das Automatisierungs-Framework Ansible. Ansible-Module für NetApp bieten eine Anleitung, wie der gewünschte Zustand definiert wird, und übertragen dies auf die NetApp Zielumgebung. Die Module werden zur Unterstützung von Aufgaben wie beispielsweise das Einrichten von Lizenzierung, Erstellen von Aggregaten und Storage Virtual Machines, Erstellen von Volumes und Wiederherstellen von Snapshots erstellt. Eine Ansible-Rolle war https://github.com/NetApp/ansible/tree/master/nar_ontap_security_ucd_guide["Veröffentlicht auf GitHub"^] speziell auf den Implementierungsleitfaden für NetApp Unified Capabilities (UC) zugeschnitten.

Mit der Bibliothek verfügbarer Module können Benutzer auf einfache Weise Ansible-Playbooks entwickeln und für die eigenen Applikationen und geschäftlichen Anforderungen anpassen, um Routineaufgaben zu automatisieren. Nachdem ein Playbook verfasst ist, können Sie es ausführen, um die angegebene Aufgabe auszuführen. Dies spart Zeit und erhöht die Produktivität. NetApp hat Beispiel-Playbooks erstellt und geteilt, die direkt verwendet oder an die eigenen Anforderungen angepasst werden können.

Data Infrastructure Insights ist ein Tool zur Infrastrukturüberwachung, das Ihnen Einblick in Ihre gesamte Infrastruktur gibt.  Mit Data Infrastructure Insights können Sie alle Ihre Ressourcen überwachen, Fehler beheben und optimieren, einschließlich Ihrer öffentlichen Cloud-Instanzen und Ihrer privaten Rechenzentren.  Data Infrastructure Insights kann die durchschnittliche Zeit bis zur Lösung um 90 % verkürzen und verhindern, dass 80 % der Cloud-Probleme Endbenutzer betreffen.  Darüber hinaus können Sie die Kosten für die Cloud-Infrastruktur um durchschnittlich 33 % senken und Ihre Anfälligkeit gegenüber Insider-Bedrohungen verringern, indem Sie Ihre Daten mit verwertbaren Informationen schützen.  Die Storage Workload Security-Funktion von Data Infrastructure Insights ermöglicht die Analyse des Benutzerverhaltens mit KI und ML, um zu warnen, wenn aufgrund einer Insider-Bedrohung abweichendes Benutzerverhalten auftritt.  Für ONTAP nutzt Storage Workload Security die Zero Trust FPolicy-Engine.
