---
sidebar: sidebar 
permalink: afx/afx-architecture.html 
keywords: netapp afx, architecture, storage availability zone, nvram, raid, disaggregated 
summary: NetApp AFX führt im Vergleich zu unified ONTAP bedeutende architektonische Unterschiede ein, wie Speicher präsentiert wird, wie Knoten mit Festplatten interagieren und wie Kapazität verwaltet wird. 
---
= Wie sich die NetApp AFX-Architektur von Unified ONTAP unterscheidet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/afx/


[role="lead"]
NetApp AFX führt im Vergleich zu unified ONTAP bedeutende architektonische Unterschiede ein, wie Speicher präsentiert wird, wie Knoten mit Festplatten interagieren und wie Kapazität verwaltet wird.

Wir haben zuvor einen allgemeinen Überblick darüber gegeben, wie die Unified ONTAP-Architektur Datei-, Objekt- und Blockdatenspeicherung über direkt verbundene HA-Paare bereitstellt, die jeweils über eigene Festplatten verfügen und physische Kapazität über Festplattenaggregate bereitstellen. In diesem Abschnitt werden wir einige der wichtigsten Unterschiede zwischen Unified ONTAP und NetApp AFX-Architekturen detaillierter erläutern.



[[how-to-tell-if-a-system-is-running-netapp-afx]]
== Wie man erkennt, ob auf einem System NetApp AFX ausgeführt wird

Die wichtigste Methode, um festzustellen, ob auf Ihrem System NetApp AFX ausgeführt wird, besteht darin, den folgenden Befehl auszuführen:

[listing]
----
AFX::> node show -fields personality
node             personality
---------------- -----------
afx-01           AFX
afx-02           AFX
----
Ein weiterer Hinweis ist die neue Storage Availability Zone, die jedoch auch für NetApp All-SAN Arrays (ASA) verfügbar ist. Ihre Kapazität können Sie über diesen Befehl anzeigen.

[listing]
----
AFX::> storage availability-zone show
                     Availability Zone Name: storage_availability_zone_0
                     Availability Zone UUID: 545cb59f-32e9-11f1-a2f5-d039eabdd925
                                 Total Size: 69.59TB
                              Physical Used: 837.1GB
                      Physical Used Percent: 1%
                                  Available: 68.77TB
                              Metadata Used: 837.1GB
                  Log and Recovery Metadata: 834.6GB
                              Delayed Frees: 2.50GB
 Physical User Data Without Snapshot Copies: 17.24MB
  Logical User Data Without Snapshot Copies: 17.24MB
   Efficiency Ratio Without Snapshot Copies: 1.00:1
               Space Full Threshold Percent: 98%
        Space Nearly Full Threshold Percent: 95%
----


[[architecture-topics]]
== Architekturthemen

* link:afx-architecture-node-disk.html["Knoten-zu-Festplatte-Beziehungen"]
* link:afx-architecture-capacity-pool.html["Einzelner Kapazitätspool"]
* link:afx-architecture-nvram-ha.html["Repliziertes NVRAM und HA Failover-Verhalten"]
* link:afx-architecture-independent-scale.html["Unabhängige, lineare Skalierung"]
* link:afx-architecture-raid.html["RAID-Änderungen"]
* link:afx-architecture-storage-efficiency.html["Speichereffizienz"]
* link:afx-architecture-feature-support.html["Änderungen der ONTAP-Funktionsunterstützung"]
* link:afx-architecture-flexgroup.html["FlexGroup Managementverbesserungen"]
* link:afx-architecture-volume-moves.html["Volume Moves"]
* link:afx-architecture-cluster-scale.html["Cluster-Skalierung"]
* link:afx-architecture-root-volume.html["Änderungen des Root-Volumes"]


[cols="1,1"]
|===


| link:afx-whats-new.html["Zurück"] | link:afx-architecture-node-disk.html["Als Nächstes: Beziehungen zwischen Knoten und Festplatte"] 
|===